### ISSUE TITLE
Choice #2 folder CRUD, will fail if JSON representation is selected

### ISSUE THREAD

**Issue by wangc31** [Enterprise-Content-Management/documentum-rest-client-java#2]
The test can be reproduced with any REST server like http://localhost:8080/dctm-rest/
Here is the error message.

```
java -jar rest-api-client-sample-7.1-all-in-one.jar
Please input the client representation type: XML JSON  [default XML]
JSON
Please input the REST context path: [default http://localhost:8080/dctm-rest]
http://localhost:8080/dctm-rest/
Please input the repository name:
REPO
Please input the username:
dmadmin
Please input the password:
password
Please input the whether add format extension .xml or .json for URI: [default false]

Please input whether print debug information: [default false]

Please input the number of the sample operation which need be executed:
0 Exit
1 Navigation
2 Folder Create/Update/Delete
3 Sysobject Create/Update/Delete
4 Document Create/Update/Delete
5 Content Management
6 Version Management
7 DQL Query
2
start Folder Create/Update/Delete sample
-------------create a folder under the Temp cabinet
Apr 19, 2016 7:29:08 PM org.springframework.web.client.RestTemplate handleResponseError
WARNING: POST request for "http://localhost:8080/dctm-rest/repositories/REPO/folders/0c00000580000107/folders" resulted in 400 (Bad Request); invoking error handler
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "id" (class com.emc.documentum.rest.client.sample.model.json.JsonRestError), not marked as ignorable (4 known properties: , "status", "details", "code", "message"])
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@670b40af; line: 1, column: 349] (through reference chain: com.emc.documentum.rest.client.sample.model.json.JsonRestError["id"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id" (class com.emc.documentum.rest.client.sample.model.json.JsonRestError), not marked as ignorable (4 known properties: , "status", "details", "code", "message"])
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@670b40af; line: 1, column: 349] (through reference chain: com.emc.documentum.rest.client.sample.model.json.JsonRestError["id"])
    at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readJavaType(MappingJackson2HttpMessageConverter.java:228)
    at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readInternal(MappingJackson2HttpMessageConverter.java:212)
    at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:158)
    at com.emc.documentum.rest.client.sample.client.impl.jackson.DCTMJacksonErrorHandler.handleError(DCTMJacksonErrorHandler.java:42)
    at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:588)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:502)
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:444)
    at com.emc.documentum.rest.client.sample.client.impl.AbstractRestTemplateClient.sendRequest(AbstractRestTemplateClient.java:201)
    at com.emc.documentum.rest.client.sample.client.impl.AbstractRestTemplateClient.post(AbstractRestTemplateClient.java:260)
    at com.emc.documentum.rest.client.sample.client.impl.jackson.DCTMJacksonClient.createFolder(DCTMJacksonClient.java:122)
    at com.emc.documentum.rest.client.sample.client.DCTMRestClientSample.crudFolder(DCTMRestClientSample.java:261)
    at com.emc.documentum.rest.client.sample.client.DCTMRestClientSample.main(DCTMRestClientSample.java:78)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id" (class com.emc.documentum.rest.client.sample.model.json.JsonRestError), not marked as ignorable (4 known properties: , "status", "details", "code", "message"])
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@670b40af; line: 1, column: 349] (through reference chain: com.emc.documentum.rest.client.sample.model.json.JsonRestError["id"])
    at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
    at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2094)
    at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readJavaType(MappingJackson2HttpMessageConverter.java:225)
    ... 12 more
```

**Comment by ruan-wei** [comment]
The new error response has new property id, which is missing for the old sample client.
