### ISSUE TITLE
NoClassDefFound com/sun/istack/Pool

### ISSUE THREAD

**Issue by MacGydver** [Enterprise-Content-Management/documentum-rest-client-java#4]
Eclipse Oxygen, Oracle JDK 1.8.0_161 When trying to build and run. The maven clean/install went fine except for the surefire reports that indicated it tried to run against default localhost url. I run, set to my rest server and  I get the following output:

Please input the client representation type: XML JSON  [default XML]

Please input the REST context path: [default http://localhost:8080/dctm-rest]
http://10.0.12.31:8080/rest
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/istack/Pool
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1138)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:441)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
	at org.springframework.http.converter.xml.AbstractJaxb2HttpMessageConverter.getJaxbContext(AbstractJaxb2HttpMessageConverter.java:111)
	at org.springframework.http.converter.xml.AbstractJaxb2HttpMessageConverter.createUnmarshaller(AbstractJaxb2HttpMessageConverter.java:79)
	at org.springframework.http.converter.xml.Jaxb2RootElementHttpMessageConverter.readFromSource(Jaxb2RootElementHttpMessageConverter.java:131)
	at org.springframework.http.converter.xml.AbstractXmlHttpMessageConverter.readInternal(AbstractXmlHttpMessageConverter.java:61)
	at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:193)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:104)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:884)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:868)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:622)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498)
	at com.emc.documentum.rest.client.sample.client.impl.AbstractRestTemplateClient$DefaultRequestProcessor.process(AbstractRestTemplateClient.java:640)
	at com.emc.documentum.rest.client.sample.client.impl.AbstractRestTemplateClient.sendRequest(AbstractRestTemplateClient.java:334)
	at com.emc.documentum.rest.client.sample.client.impl.AbstractRestTemplateClient.get(AbstractRestTemplateClient.java:417)
	at com.emc.documentum.rest.client.sample.client.impl.jaxb.DCTMJaxbClient.getHomeDocument(DCTMJaxbClient.java:145)
	at com.emc.documentum.rest.client.sample.client.impl.jaxb.DCTMJaxbClient.getRepositories(DCTMJaxbClient.java:161)
	at com.emc.documentum.rest.client.sample.client.DCTMRestClientBuilder.getRepositories(DCTMRestClientBuilder.java:121)
	at com.emc.documentum.rest.client.sample.client.DCTMRestClientBuilder.buildWithPrompt(DCTMRestClientBuilder.java:49)
	at com.emc.documentum.rest.client.sample.DCTMRestClientSample.main(DCTMRestClientSample.java:26)
Caused by: java.lang.ClassNotFoundException: com.sun.istack.Pool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more

**Comment by ruan-wei** [comment]
looks like you need include jaxb-core and jaxb-impl jars in your project.

**Comment by ruan-wei** [comment]
the jaxb-core is depending on the istack-commons-runtime, which can be found in the pom of the jaxb-core.

**Comment by MacGydver** [comment]
I built from maven pom in the project. I will get back to it soon. Looks like jvm 8 changed some core libraries that are depended on so i will go back to jvm 7 rather than just using build env with java 7 set.

Thanks for the response

On Feb 24, 2018, at 12:36 AM, Wei Ruan <notifications@github.com<mailto:notifications@github.com>> wrote:


the jaxb-core is depending on the istack-commons-runtime, which can be found in the pom of the jaxb-core.

**Comment by ruan-wei** [comment]
I tried with jvm 8 build 152. It works well.
Since the jaxb dependency is hard coded in the root pom file, I don't know why istack is not included.
Did you manually exclude it from your pom?

**Comment by MacGydver** [comment]
I figured it out. When I imported as a Maven project in Eclipse, it had a Java Execution environment Library (1.7) and Runtime Environment Library set. I removed the execution environment library and it is running now.
